import Login from "@/components/Login";
import Modal from "@/components/Modal";
import Sidebar from "@/components/Sidebar";
import SinglePost from "@/components/SinglePost";
import Trending from "@/components/Trending";
import { AppContext } from "@/contexts/AppContext";
import { getSession, useSession } from "next-auth/react";
import Head from "next/head";
import React, { useContext } from "react";

export default function PostPage() {
  const { data: session } = useSession();
  const [appContext] = useContext(AppContext);

  if (!session) return <Login />;

  return (
    <div>
      <Head>
        <title>Twitter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col sm:flex-row w-full xl:max-w-screen-xl mx-auto px-8 sm:px-12">
        <Sidebar />
        <div className="flex gap-6 overflow-y-scroll h-screen flex-1">
          <SinglePost />
          <Trending />
          {appContext?.isModalOpen && <Modal />}
        </div>
      </main>
    </div>
  );
}

export async function getServerSideProps(context) {
  const session = await getSession(context);
  return {
    props: {
      session,
    },
  };
}
