import Head from "next/head";
import { getSession, useSession } from "next-auth/react";
import Login from "../components/Login";
import Sidebar from "../components/Sidebar";
import Feed from "../components/Feed";
import Trending from "@/components/Trending";
import Modal from "@/components/Modal";
import { useContext } from "react";
import { AppContext } from "@/contexts/AppContext";

export default function Home() {
  const [appContext] = useContext(AppContext);
  const { data: session } = useSession();
  if (!session) return <Login />;

  return (
    <>
      <Head>
        <title>Twitter Clone</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col sm:flex-row w-full xl:max-w-screen-xl mx-auto px-8 sm:px-12">
        <Sidebar />
        <div className="flex gap-6 overflow-y-scroll h-screen flex-1">
          <Feed />
          <Trending />
          {appContext?.isModalOpen && <Modal />}
        </div>
      </main>
    </>
  );
}

export async function getServerSideProps(context) {
  const session = await getSession(context);

  return {
    props: {
      session,
    },
  };
}
